# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "bilibili"
name = "Bç«™"
url = "https://space.bilibili.com/110874572"

[social.params]
icon = "bilibili"
